name: Trigger auto deployment for fevicol

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fevicol-AutoDeployTrigger-d1cfed39-8591-4747-a6bd-23d3808180eb.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.FEVICOL_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FEVICOL_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FEVICOL_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }} 
          registryUrl: 
          registryUsername: ${{ secrets.FEVICOL_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FEVICOL_REGISTRY_PASSWORD }}
          containerAppName: fevicol
          resourceGroup: anony
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


